-- BERL website admin setup
-- Run this file once in Supabase > SQL Editor.

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  date date not null default current_date,
  category text not null default 'News',
  title text not null,
  summary text not null default '',
  image text not null default '',
  body jsonb not null default '[]'::jsonb,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.news enable row level security;
alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

grant execute on function public.is_admin() to authenticated;

grant select on public.news to anon, authenticated;
grant insert, update, delete on public.news to authenticated;

drop policy if exists "Public can read published news" on public.news;
create policy "Public can read published news"
on public.news
for select
to anon, authenticated
using (is_published = true or public.is_admin());

drop policy if exists "Admins can insert news" on public.news;
create policy "Admins can insert news"
on public.news
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update news" on public.news;
create policy "Admins can update news"
on public.news
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete news" on public.news;
create policy "Admins can delete news"
on public.news
for delete
to authenticated
using (public.is_admin());

-- admin_users stays private; access is only through the security-definer is_admin() function.
revoke all on public.admin_users from anon, authenticated;

-- After creating your administrator under Supabase > Authentication > Users,
-- copy that user's UUID and run this once, replacing the sample UUID:
-- insert into public.admin_users (user_id)
-- values ('00000000-0000-0000-0000-000000000000')
-- on conflict (user_id) do nothing;
